step_time: 0.001
missile_configs {
  missile_type: HYDRA_70
  initial_state {
    position {
      x: 0
      y: 0
      z: 0
    }
    velocity {
      x: 1e-3
      y: 0
      z: 2e-3
    }
  }
  dynamic_config {
    launch_config {
      launch_time: 0
    }
  }
  plotting_config {
    color: BLUE
    linestyle: DOTTED
    marker: TRIANGLE_UP
  }
  submunitions_config {
    num_submunitions: 7
    launch_config {
      launch_time: 10
    }
    agent_config {
      missile_type: MICROMISSILE
      dynamic_config {
        sensor_config {
          type: IDEAL
          frequency: 100
        }
      }
      plotting_config {
        color: BLUE
        linestyle: SOLID
        marker: TRIANGLE_DOWN
      }
    }
  }
}
missile_configs {
  missile_type: HYDRA_70
  initial_state {
    position {
      x: 0
      y: 0
      z: 0
    }
    velocity {
      x: 1e-3
      y: 0
      z: 2e-3
    }
  }
  dynamic_config {
    launch_config {
      launch_time: 0
    }
  }
  plotting_config {
    color: BLUE
    linestyle: DOTTED
    marker: TRIANGLE_UP
  }
  submunitions_config {
    num_submunitions: 7
    launch_config {
      launch_time: 10
    }
    agent_config {
      missile_type: MICROMISSILE
      dynamic_config {
        sensor_config {
          type: IDEAL
          frequency: 100
        }
      }
      plotting_config {
        color: BLUE
        linestyle: SOLID
        marker: TRIANGLE_DOWN
      }
    }
  }
}
missile_configs {
  missile_type: HYDRA_70
  initial_state {
    position {
      x: 0
      y: 10
      z: 0
    }
    velocity {
      x: 1e-3
      y: 0
      z: 2e-3
    }
  }
  dynamic_config {
    launch_config {
      launch_time: 5
    }
  }
  plotting_config {
    color: GREEN
    linestyle: DOTTED
    marker: TRIANGLE_UP
  }
  submunitions_config {
    num_submunitions: 7
    launch_config {
      launch_time: 10
    }
    agent_config {
      missile_type: MICROMISSILE
      dynamic_config {
        sensor_config {
          type: IDEAL
          frequency: 100
        }
      }
      plotting_config {
        color: GREEN
        linestyle: SOLID
        marker: TRIANGLE_DOWN
      }
    }
  }
}
missile_configs {
  missile_type: HYDRA_70
  initial_state {
    position {
      x: 0
      y: 10
      z: 0
    }
    velocity {
      x: 1e-3
      y: 0
      z: 2e-3
    }
  }
  dynamic_config {
    launch_config {
      launch_time: 5
    }
  }
  plotting_config {
    color: GREEN
    linestyle: DOTTED
    marker: TRIANGLE_UP
  }
  submunitions_config {
    num_submunitions: 7
    launch_config {
      launch_time: 10
    }
    agent_config {
      missile_type: MICROMISSILE
      dynamic_config {
        sensor_config {
          type: IDEAL
          frequency: 100
        }
      }
      plotting_config {
        color: GREEN
        linestyle: SOLID
        marker: TRIANGLE_DOWN
      }
    }
  }
}
target_configs {
  target_type: DRONE
  initial_state {
    position {
      x: 10000
      y: 0
      z: 150
    }
    velocity {
      x: -40
      y: -20
      z: 0
    }
  }
  plotting_config {
    color: RED
    linestyle: SOLID
    marker: SQUARE
  }
}
